# Generated by Django 5.2.7 on 2025-10-17 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
    ]
