# Generated by Django 5.2.7 on 2025-10-18 03:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0004_alter_categoria_descripcion_alter_categoria_nombre_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Número de factura')),
                ('fecha_emision', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de emisión')),
                ('nombre_cliente', models.CharField(max_length=200, verbose_name='Nombre del cliente')),
                ('documento_cliente', models.CharField(blank=True, max_length=20, verbose_name='Documento de identidad')),
                ('direccion_cliente', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('telefono_cliente', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email_cliente', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('con_iva', models.BooleanField(default=True, verbose_name='Aplicar IVA')),
                ('porcentaje_iva', models.DecimalField(decimal_places=2, default=19.0, max_digits=5, verbose_name='Porcentaje IVA')),
                ('valor_iva', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to=settings.AUTH_USER_MODEL)),
                ('vendedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='ItemFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ventas.factura')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Item de factura',
                'verbose_name_plural': 'Items de factura',
            },
        ),
    ]
