# Generated by Django 5.2.7 on 2025-11-21 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREATE', 'Crear'), ('UPDATE', 'Actualizar'), ('DELETE', 'Eliminar'), ('VIEW', 'Ver')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modelo', models.CharField(db_index=True, max_length=100)),
                ('objeto_id', models.PositiveIntegerField()),
                ('objeto_nombre', models.CharField(blank=True, max_length=255)),
                ('datos_anteriores', models.JSONField(blank=True, null=True)),
                ('datos_nuevos', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('descripcion', models.TextField()),
                ('cambios_resumidos', models.JSONField(blank=True, default=dict)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='HistorialCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_id', models.PositiveIntegerField()),
                ('nombre_anterior', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_nuevo', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion_anterior', models.TextField(blank=True, null=True)),
                ('descripcion_nueva', models.TextField(blank=True, null=True)),
                ('audit_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auditorias.auditlog')),
            ],
            options={
                'verbose_name': 'Historial de Categoría',
                'verbose_name_plural': 'Historiales de Categoría',
            },
        ),
        migrations.CreateModel(
            name='HistorialCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_id', models.PositiveIntegerField()),
                ('cambios', models.JSONField()),
                ('audit_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auditorias.auditlog')),
            ],
            options={
                'verbose_name': 'Historial de Cliente',
                'verbose_name_plural': 'Historiales de Cliente',
            },
        ),
        migrations.CreateModel(
            name='HistorialCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cotizacion_id', models.PositiveIntegerField()),
                ('estado_anterior', models.CharField(blank=True, max_length=50, null=True)),
                ('estado_nuevo', models.CharField(blank=True, max_length=50, null=True)),
                ('monto_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monto_nuevo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('audit_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auditorias.auditlog')),
            ],
            options={
                'verbose_name': 'Historial de Cotización',
                'verbose_name_plural': 'Historiales de Cotización',
            },
        ),
        migrations.CreateModel(
            name='HistorialFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factura_id', models.PositiveIntegerField()),
                ('monto_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monto_nuevo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado_anterior', models.CharField(blank=True, max_length=50, null=True)),
                ('estado_nuevo', models.CharField(blank=True, max_length=50, null=True)),
                ('audit_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auditorias.auditlog')),
            ],
            options={
                'verbose_name': 'Historial de Factura',
                'verbose_name_plural': 'Historiales de Factura',
            },
        ),
        migrations.CreateModel(
            name='HistorialPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido_id', models.PositiveIntegerField()),
                ('estado_anterior', models.CharField(blank=True, max_length=50, null=True)),
                ('estado_nuevo', models.CharField(blank=True, max_length=50, null=True)),
                ('total_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_nuevo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cliente_anterior', models.CharField(blank=True, max_length=255, null=True)),
                ('cliente_nuevo', models.CharField(blank=True, max_length=255, null=True)),
                ('audit_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auditorias.auditlog')),
            ],
            options={
                'verbose_name': 'Historial de Pedido',
                'verbose_name_plural': 'Historiales de Pedido',
            },
        ),
        migrations.CreateModel(
            name='HistorialProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_id', models.PositiveIntegerField()),
                ('precio_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_nuevo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock_anterior', models.IntegerField(blank=True, null=True)),
                ('stock_nuevo', models.IntegerField(blank=True, null=True)),
                ('estado_anterior', models.CharField(blank=True, max_length=50, null=True)),
                ('estado_nuevo', models.CharField(blank=True, max_length=50, null=True)),
                ('audit_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auditorias.auditlog')),
            ],
            options={
                'verbose_name': 'Historial de Producto',
                'verbose_name_plural': 'Historiales de Producto',
            },
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['usuario', '-timestamp'], name='auditorias__usuario_6b65e1_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['modelo', '-timestamp'], name='auditorias__modelo_f15114_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['accion', '-timestamp'], name='auditorias__accion_780373_idx'),
        ),
    ]
