# Generated by Django 5.2.7 on 2025-11-21 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('cotizaciones', '0002_cotizacion_incluir_iva'),
        ('inventario', '0004_alter_categoria_descripcion_alter_categoria_nombre_and_more'),
        ('pedidos', '0003_remove_cliente_fecha_creacion_alter_cliente_apellido_and_more'),
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('nombre_anterior', models.CharField(blank=True, max_length=100)),
                ('nombre_nuevo', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.TextField(verbose_name='Descripción del cambio')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='inventario.categoria', verbose_name='Categoría')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historial de categoría',
                'verbose_name_plural': 'Historiales de categorías',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='HistorialCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('cambios', models.JSONField(blank=True, default=dict, verbose_name='Cambios realizados')),
                ('descripcion', models.TextField(verbose_name='Descripción del cambio')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='pedidos.cliente', verbose_name='Cliente')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historial de cliente',
                'verbose_name_plural': 'Historiales de clientes',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='HistorialCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('estado_anterior', models.CharField(blank=True, max_length=20)),
                ('estado_nuevo', models.CharField(blank=True, max_length=20)),
                ('total_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_nuevo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('descripcion', models.TextField(verbose_name='Descripción del cambio')),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='cotizaciones.cotizacion', verbose_name='Cotización')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historial de cotización',
                'verbose_name_plural': 'Historiales de cotizaciones',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='HistorialFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('estado_anterior', models.CharField(blank=True, max_length=20)),
                ('estado_nuevo', models.CharField(blank=True, max_length=20)),
                ('total_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_nuevo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('descripcion', models.TextField(verbose_name='Descripción del cambio')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='ventas.factura', verbose_name='Factura')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historial de factura',
                'verbose_name_plural': 'Historiales de facturas',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='HistorialPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('estado_anterior', models.CharField(blank=True, max_length=20)),
                ('estado_nuevo', models.CharField(blank=True, max_length=20)),
                ('descripcion', models.TextField(verbose_name='Descripción del cambio')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='pedidos.pedido', verbose_name='Pedido')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historial de pedido',
                'verbose_name_plural': 'Historiales de pedidos',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='HistorialProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('nombre_anterior', models.CharField(blank=True, max_length=100)),
                ('nombre_nuevo', models.CharField(blank=True, max_length=100)),
                ('precio_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_nuevo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock_anterior', models.IntegerField(blank=True, null=True)),
                ('stock_nuevo', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.TextField(verbose_name='Descripción del cambio')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='inventario.producto', verbose_name='Producto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historial de producto',
                'verbose_name_plural': 'Historiales de productos',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_nombre', models.CharField(help_text='Se guarda por si el usuario se elimina', max_length=200, verbose_name='Nombre de usuario')),
                ('accion', models.CharField(choices=[('CREATE', 'Crear'), ('UPDATE', 'Actualizar'), ('DELETE', 'Eliminar')], max_length=10, verbose_name='Acción')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha y hora')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID del objeto')),
                ('modelo', models.CharField(db_index=True, max_length=100, verbose_name='Modelo')),
                ('objeto_repr', models.CharField(max_length=200, verbose_name='Representación del objeto')),
                ('cambios', models.JSONField(blank=True, default=dict, help_text='Datos anteriores y nuevos en formato JSON', verbose_name='Cambios realizados')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('notas', models.TextField(blank=True, verbose_name='Notas adicionales')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de contenido')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de auditoría',
                'verbose_name_plural': 'Registros de auditoría',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['-fecha_hora'], name='auditorias__fecha_h_eef3ed_idx'), models.Index(fields=['modelo', '-fecha_hora'], name='auditorias__modelo_c50b90_idx'), models.Index(fields=['usuario', '-fecha_hora'], name='auditorias__usuario_d050ed_idx'), models.Index(fields=['accion', '-fecha_hora'], name='auditorias__accion_596a14_idx')],
            },
        ),
    ]
