# Generated by Django 5.2.7 on 2025-11-21 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historialcategoria',
            options={'ordering': ['-audit_log__timestamp'], 'verbose_name': 'Historial de Categoría', 'verbose_name_plural': 'Historiales de Categoría'},
        ),
        migrations.AlterModelOptions(
            name='historialcliente',
            options={'ordering': ['-audit_log__timestamp'], 'verbose_name': 'Historial de Cliente', 'verbose_name_plural': 'Historiales de Cliente'},
        ),
        migrations.AlterModelOptions(
            name='historialcotizacion',
            options={'ordering': ['-audit_log__timestamp'], 'verbose_name': 'Historial de Cotización', 'verbose_name_plural': 'Historiales de Cotización'},
        ),
        migrations.AlterModelOptions(
            name='historialfactura',
            options={'ordering': ['-audit_log__timestamp'], 'verbose_name': 'Historial de Factura', 'verbose_name_plural': 'Historiales de Factura'},
        ),
        migrations.AlterModelOptions(
            name='historialpedido',
            options={'ordering': ['-audit_log__timestamp'], 'verbose_name': 'Historial de Pedido', 'verbose_name_plural': 'Historiales de Pedido'},
        ),
        migrations.AlterModelOptions(
            name='historialproducto',
            options={'ordering': ['-audit_log__timestamp'], 'verbose_name': 'Historial de Producto', 'verbose_name_plural': 'Historiales de Producto'},
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='auditorias__accion_780373_idx',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='cambios_resumidos',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='datos_anteriores',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='datos_nuevos',
        ),
        migrations.RemoveField(
            model_name='historialpedido',
            name='total_anterior',
        ),
        migrations.RemoveField(
            model_name='historialpedido',
            name='total_nuevo',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='cambios',
            field=models.JSONField(blank=True, help_text='Solo los campos que cambiaron', null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='datos_anterior',
            field=models.JSONField(blank=True, help_text='Datos antes de la modificación', null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='datos_nuevo',
            field=models.JSONField(blank=True, help_text='Datos después de la modificación', null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='accion',
            field=models.CharField(choices=[('CREATE', '✅ CREADO'), ('UPDATE', '🔄 ACTUALIZADO'), ('DELETE', '❌ ELIMINADO'), ('VIEW', '👁️ VISUALIZADO')], max_length=20),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='modelo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='objeto_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='objeto_nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historialcategoria',
            name='audit_log',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historial_categoria', to='auditorias.auditlog'),
        ),
        migrations.AlterField(
            model_name='historialcategoria',
            name='categoria_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='historialcategoria',
            name='nombre_anterior',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historialcategoria',
            name='nombre_nuevo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historialcliente',
            name='audit_log',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historial_cliente', to='auditorias.auditlog'),
        ),
        migrations.AlterField(
            model_name='historialcliente',
            name='cambios',
            field=models.JSONField(help_text='Cambios realizados'),
        ),
        migrations.AlterField(
            model_name='historialcliente',
            name='cliente_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='historialcotizacion',
            name='audit_log',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historial_cotizacion', to='auditorias.auditlog'),
        ),
        migrations.AlterField(
            model_name='historialcotizacion',
            name='cotizacion_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='historialfactura',
            name='audit_log',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historial_factura', to='auditorias.auditlog'),
        ),
        migrations.AlterField(
            model_name='historialfactura',
            name='factura_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='historialpedido',
            name='audit_log',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historial_pedido', to='auditorias.auditlog'),
        ),
        migrations.AlterField(
            model_name='historialpedido',
            name='pedido_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='historialproducto',
            name='audit_log',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historial_producto', to='auditorias.auditlog'),
        ),
        migrations.AlterField(
            model_name='historialproducto',
            name='producto_id',
            field=models.IntegerField(),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['-timestamp'], name='auditorias__timesta_5aa309_idx'),
        ),
    ]
