# Generated by Django 5.2.7 on 2025-11-10 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='incluir_iva',
            field=models.BooleanField(default=True, verbose_name='Incluir IVA (19%)'),
        ),
    ]
